### ISSUE TITLE
hi,i has a question when i install this,please help me! 

### ISSUE THREAD

**Issue by sunminghong** [qiniu/py#20]
$ go build
# pkg-config --cflags python-2.7

Package python-2.7 was not found in the pkg-config search path.
Perhaps you should add the directory containing `python-2.7.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python-2.7' found
exit status 1

**Comment by wenhaoZhao1997** [comment]
> sudo apt-get install python2.7-dev

No package python2.7-dev available

**Comment by xushiwei** [comment]
This package is unmaintained. I suggest you use other replacement.
