### ISSUE TITLE
Parse传递\0字符串时会被截断

### ISSUE THREAD

**Issue by lsaint** [qiniu/py#22]
怎样在python中带\0的二进制字符串传递到go？go端用string放入Parse解析这种字符串时会被截断。

**Comment by xiyanxiyan10** [comment]
这应该是在python转go的过程中经过c的原因，c会认为buffer中的“\0”为字符串结尾。
可能只能先把string中的\0这样的符号编码为特殊符号替换，go拿到的时候再反解编码
